#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2013 by Delphix. All rights reserved.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/net_include.sh

# Make sure that the libraries essential to this stage of booting can be found.
LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH

#
# Store the /etc/hosts loopback hostname mapping so that we can update it
# when the hostname is later changed.
#
save_loopback_mapping()
{
	mapping=$1
	/usr/sbin/svccfg -s $SMF_FMRI setprop config/loopback = $mapping || \
	    return 1
	/usr/sbin/svccfg -s $SMF_FMRI refresh
}

add_loopback_mapping()
{
	new_hostname=$1

	if ! ggrep '\b'"$new_hostname"'\b' /etc/inet/hosts; then
		tmp_hosts=$(mktemp -t hosts.XXXX)

		gsed -e '/^127.0.0.1/ s/$/ '"$new_hostname"'/' \
		    -e '/^::1/ s/$/ '"$new_hostname"'/' /etc/inet/hosts \
		    >$tmp_hosts
		if [[ $? -ne 0 ]]; then
			return 1
		fi

		cp $tmp_hosts /etc/inet/hosts || return 1
		rm -f $tmp_hosts
	fi

	save_loopback_mapping $new_hostname
	return $?
}

update_loopback_mapping()
{
	old_hostname=$1
	new_hostname=$2
	tmp_hosts=$(mktemp -t hosts.XXXX)

	if ! ggrep '\b'"$new_hostname"'\b' /etc/inet/hosts; then
		gsed -e \
		    '/^127.0.0.1/ s/\b'"$old_hostname"'\b/'"$new_hostname"'/g' \
		    -e '/^::1/ s/\b'"$old_hostname"'\b/'"$new_hostname"'/g' \
		    /etc/inet/hosts >$tmp_hosts
		if [[ $? -ne 0 ]]; then
			return 1
		fi

		cp $tmp_hosts /etc/inet/hosts || return 1
		rm -f $tmp_hosts
	fi

	save_loopback_mapping $new_hostname
	return $?
}

#
# Set the hostname either from the local /etc/nodename file or from the network
# (DHCP or RPC bootparams).  If no hostname was set via any of these methods,
# then set it to "unknown" (it needs to be set to _something_ as expected by
# countless applications).  We then ensure that an /etc/hosts loopback addres
# mapping exists for the hostname, as many applications expect the hostname to
# resolve to a local address.
#
# For non-global zones, fall back to the `uname -n` value provided by the
# kernel if /etc/nodename does not exist, as is expected on an initial boot.
#

smf_netstrategy

case "$_INIT_NET_STRATEGY" in
"dhcp") hostname=$(/sbin/dhcpinfo Hostname) ;;
"rarp") hostname=$(/sbin/hostconfig -h -p bootparams)
	trap 'intr=1' 2 3
	while [[ -z "$hostname" && ! -f /etc/.UNCONFIGURED && -z "$intr" ]]; do
		echo "re-trying host configuration..."
		# Restrict this to IPv4 interfaces.
		/sbin/ifconfig -adD4 auto-revarp up
		hostname=$(/sbin/hostconfig -h -p bootparams)
	done
	trap 2 3 ;;
"none") hostname="$(shcat /etc/nodename 2>/dev/null)"
	if [[ -z "$hostname" ]]; then
		if smf_is_globalzone; then
			hostname=$(/sbin/hostconfig -h -p bootparams)
		else
			hostname=$(/sbin/uname -n)
		fi
	fi ;;
esac

local_override=$(/usr/bin/svcprop -p config/local_override $SMF_FMRI)
if [[ -z "$hostname" || "$local_override" = "true" ]]; then
	hostname="$(shcat /etc/nodename 2>/dev/null)"
	if [[ -z "$hostname" ]]; then
		hostname="unknown"
	fi
fi

/sbin/uname -S $hostname

#
# Create or update the hostname /etc/hosts loopback mapping if the management
# of the mapping is enabled.
#
enable_mapping=$(/usr/bin/svcprop -p config/enable_mapping $SMF_FMRI)
if [[ "$enable_mapping" = "true" ]]; then
	mapping=$(/usr/bin/svcprop -p config/loopback $SMF_FMRI)
	if [[ "$mapping" = '""' ]]; then
		#
		# During the first boot after installation, there is no
		# existing /etc/hosts mapping.
		#
		add_loopback_mapping $hostname || exit $SMF_ERR_FATAL
	elif [[ "$mapping" != "$hostname" ]]; then
		#
		# The hostname has changed since this service was last enabled
		# or refreshed.  We need to update the /etc/hosts mapping.
		#
		update_loopback_mapping $mapping $hostname || \
		    exit $SMF_ERR_FATAL
	fi
fi

echo "Hostname: $(/sbin/uname -n)" > /dev/msglog

# Reset the library path now that we are past the critical stage
unset LD_LIBRARY_PATH

exit $SMF_EXIT_OK
