#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012, 2017 by Delphix. All rights reserved.
# Copyright 2016, OmniTI Computer Consulting, Inc. All rights reserved.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 1800
post_user = root
post = cleanup
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/functional/acl/cifs]
find_tests = true

[/opt/zfs-tests/tests/functional/acl/nontrivial]
find_tests = true

[/opt/zfs-tests/tests/functional/acl/trivial]
find_tests = true

[/opt/zfs-tests/tests/functional/atime]
find_tests = true

[/opt/zfs-tests/tests/functional/bootfs]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/cache]
find_tests = true

[/opt/zfs-tests/tests/functional/cachefile]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/casenorm]
find_tests = true

[/opt/zfs-tests/tests/functional/checksum]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/clean_mirror]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zdb]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zfs]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_clone]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_copies]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_create]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_destroy]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_get]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_inherit]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_mount]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_promote]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_property]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_receive]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_rename]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_reservation]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_rollback]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_send]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_set]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_share]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_snapshot]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_unmount]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_unshare]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zfs_upgrade]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_add]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_attach]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_clear]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_create]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_destroy]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_detach]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_expand]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_export]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_get]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_history]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_import]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_labelclear]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_offline]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_online]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_remove]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_replace]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_scrub]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_set]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_status]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_root/zpool_upgrade]
find_tests = true

[/opt/zfs-tests/tests/functional/cli_user/misc]
find_tests = true
user =

[/opt/zfs-tests/tests/functional/cli_user/zfs_list]
find_tests = true
user =

[/opt/zfs-tests/tests/functional/cli_user/zpool_iostat]
find_tests = true
user =

[/opt/zfs-tests/tests/functional/cli_user/zpool_list]
find_tests = true
user =

[/opt/zfs-tests/tests/functional/compression]
find_tests = true

[/opt/zfs-tests/tests/functional/ctime]
find_tests = true

[/opt/zfs-tests/tests/functional/delegate]
find_tests = true

[/opt/zfs-tests/tests/functional/devices]
find_tests = true

[/opt/zfs-tests/tests/functional/exec]
find_tests = true

[/opt/zfs-tests/tests/functional/features/async_destroy]
find_tests = true

[/opt/zfs-tests/tests/functional/grow_pool]
find_tests = true

[/opt/zfs-tests/tests/functional/grow_replicas]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/history]
find_tests = true

[/opt/zfs-tests/tests/functional/holes]
find_tests = true

[/opt/zfs-tests/tests/functional/inheritance]
find_tests = true
pre =

[/opt/zfs-tests/tests/functional/inuse]
find_tests = true
post =

[/opt/zfs-tests/tests/functional/large_files]
find_tests = true

[/opt/zfs-tests/tests/functional/largest_pool]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/libzfs]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/link_count]
find_tests = true

[/opt/zfs-tests/tests/functional/mdb]
find_tests = true

[/opt/zfs-tests/tests/functional/migration]
find_tests = true

[/opt/zfs-tests/tests/functional/mmap]
find_tests = true

[/opt/zfs-tests/tests/functional/mount]
find_tests = true

[/opt/zfs-tests/tests/functional/mv_files]
find_tests = true

[/opt/zfs-tests/tests/functional/nestedfs]
find_tests = true

[/opt/zfs-tests/tests/functional/no_space]
find_tests = true

[/opt/zfs-tests/tests/functional/nopwrite]
find_tests = true

[/opt/zfs-tests/tests/functional/online_offline]
find_tests = true

[/opt/zfs-tests/tests/functional/pool_names]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/poolversion]
find_tests = true

[/opt/zfs-tests/tests/functional/privilege]
find_tests = true

[/opt/zfs-tests/tests/functional/quota]
find_tests = true

[/opt/zfs-tests/tests/functional/redundancy]
find_tests = true

[/opt/zfs-tests/tests/functional/refquota]
find_tests = true

[/opt/zfs-tests/tests/functional/refreserv]
find_tests = true

[/opt/zfs-tests/tests/functional/rename_dirs]
find_tests = true

[/opt/zfs-tests/tests/functional/replacement]
find_tests = true

[/opt/zfs-tests/tests/functional/reservation]
find_tests = true

[/opt/zfs-tests/tests/functional/rootpool]
find_tests = true

[/opt/zfs-tests/tests/functional/rsend]
find_tests = true

[/opt/zfs-tests/tests/functional/scrub_mirror]
find_tests = true

[/opt/zfs-tests/tests/functional/slog]
find_tests = true

[/opt/zfs-tests/tests/functional/snapshot]
find_tests = true

[/opt/zfs-tests/tests/functional/snapused]
find_tests = true

[/opt/zfs-tests/tests/functional/sparse]
find_tests = true

[/opt/zfs-tests/tests/functional/threadsappend]
find_tests = true

[/opt/zfs-tests/tests/functional/truncate]
find_tests = true

[/opt/zfs-tests/tests/functional/userquota]
find_tests = true

[/opt/zfs-tests/tests/functional/utils_test]
find_tests = true

[/opt/zfs-tests/tests/functional/vdev_zaps]
find_tests = true

[/opt/zfs-tests/tests/functional/write_dirs]
find_tests = true

[/opt/zfs-tests/tests/functional/xattr]
find_tests = true

[/opt/zfs-tests/tests/functional/zvol/zvol_ENOSPC]
find_tests = true

[/opt/zfs-tests/tests/functional/zvol/zvol_cli]
find_tests = true

[/opt/zfs-tests/tests/functional/zvol/zvol_dump]
find_tests = true
pre =
post =

[/opt/zfs-tests/tests/functional/zvol/zvol_misc]
find_tests = true
