#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
#

[DEFAULT]
pre =
quiet = False
pre_user = root
user = root
timeout = 60
post_user = root
post =
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/functional/acl/cifs]
tests = ['cifs_attr_001_pos', 'cifs_attr_002_pos', 'cifs_attr_003_pos']
pre = /opt/zfs-tests/tests/functional/acl/cifs/setup
post = /opt/zfs-tests/tests/functional/acl/cifs/cleanup

[/opt/zfs-tests/tests/functional/acl/nontrivial]
tests = ['zfs_acl_chmod_001_neg', 'zfs_acl_chmod_002_pos',
    'zfs_acl_chmod_aclmode_001_pos', 'zfs_acl_chmod_compact_001_pos',
    'zfs_acl_chmod_delete_001_pos', 'zfs_acl_chmod_inherit_001_pos',
    'zfs_acl_chmod_inherit_002_neg', 'zfs_acl_chmod_inherit_002_pos',
    'zfs_acl_chmod_inherit_003_pos', 'zfs_acl_chmod_inherit_004_pos',
    'zfs_acl_chmod_owner_001_pos', 'zfs_acl_chmod_rwacl_001_pos',
    'zfs_acl_chmod_rwx_001_pos', 'zfs_acl_chmod_rwx_002_pos',
    'zfs_acl_chmod_rwx_003_pos', 'zfs_acl_chmod_rwx_004_pos',
    'zfs_acl_chmod_xattr_001_pos', 'zfs_acl_chmod_xattr_002_pos',
    'zfs_acl_cp_001_pos', 'zfs_acl_cp_002_pos', 'zfs_acl_cpio_001_pos',
    'zfs_acl_cpio_002_pos', 'zfs_acl_find_001_pos', 'zfs_acl_ls_001_pos',
    'zfs_acl_mv_001_pos', 'zfs_acl_tar_001_pos', 'zfs_acl_tar_002_pos']
pre = /opt/zfs-tests/tests/functional/acl/nontrivial/setup
post = /opt/zfs-tests/tests/functional/acl/nontrivial/cleanup
timeout = 120

[/opt/zfs-tests/tests/functional/acl/trivial]
tests = ['zfs_acl_chmod_001_pos', 'zfs_acl_compress_001_pos',
    'zfs_acl_cp_001_pos', 'zfs_acl_cp_002_neg', 'zfs_acl_cp_003_neg',
    'zfs_acl_find_001_pos', 'zfs_acl_find_002_neg', 'zfs_acl_ls_001_pos',
    'zfs_acl_ls_002_neg', 'zfs_acl_mv_001_pos', 'zfs_acl_pack_001_pos',
    'zfs_acl_pax_001_pos', 'zfs_acl_pax_002_pos', 'zfs_acl_pax_003_pos',
    'zfs_acl_pax_004_pos', 'zfs_acl_pax_005_pos', 'zfs_acl_pax_006_pos',
    'zfs_acl_tar_001_pos', 'zfs_acl_tar_002_neg']
pre = /opt/zfs-tests/tests/functional/acl/trivial/setup
post = /opt/zfs-tests/tests/functional/acl/trivial/cleanup

[/opt/zfs-tests/tests/functional/atime]
tests = ['atime_001_pos', 'atime_002_neg']
pre=/opt/zfs-tests/tests/functional/atime/setup
post=/opt/zfs-tests/tests/functional/atime/cleanup

[/opt/zfs-tests/tests/functional/bootfs]
tests = ['bootfs_001_pos', 'bootfs_002_neg', 'bootfs_003_pos', 'bootfs_004_neg',
    'bootfs_005_neg', 'bootfs_006_pos', 'bootfs_007_neg', 'bootfs_008_neg']

[/opt/zfs-tests/tests/functional/truncate]
tests = ['truncate_001_pos', 'truncate_002_pos']
pre = /opt/zfs-tests/tests/functional/truncate/setup
post = /opt/zfs-tests/tests/functional/truncate/cleanup

