#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1999, 2010, Oracle and/or its affiliates. All rights reserved.
# Copyright 2012 Milan Jurik. All rights reserved.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
#
# This is the start method for the network/datalink:default SMF service
# instance.  It is responsible for discoverying new physical datalinks on
# reconfigure boot, and enabling administratively created datalinks such as
# VNICs and link aggregations.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/net_include.sh

#
# This service does nothing in non-global zones.
#
if ! smf_is_globalzone; then
	exit $SMF_EXIT_OK
fi

net_reconfigure || exit $SMF_EXIT_ERR_CONFIG

# Update PVID on interfaces configured with VLAN 1
update_pvid

#
# Upgrade handling.  The upgrade file consists of a series of dladm(1M)
# commands.  Note that after we are done, we cannot rename the upgrade script
# file as the file system is still read-only at this point.  Defer this to the
# manifest-import service.
#
upgrade_script=/var/svc/profile/upgrade_datalink
if [ -f "${upgrade_script}" ]; then
	. "${upgrade_script}"
fi

#
# Upgrade handling for ibd:
# After we are done with the upgrade handling, we can not set the
# ibd/ibd_upgraded property to "true" as the file system is read-only at this
# point. It will be done later by ibd-post-upgrade service.
#
if [ -x /sbin/ibd_upgrade ]; then
	ibd_upgraded=`/bin/svcprop -c -p ibd/ibd_upgraded \
	$SMF_FMRI 2> /dev/null`
	if [ "$ibd_upgraded" != "true" ]; then
		/sbin/ibd_upgrade -v
	fi
fi

#
# Enable administratively-created datalinks and initialize security objects.
# Note that link property initialization is deferred until after IP interfaces
# are plumbed in network/physical to ensure that the links will not be unloaded
# (and the property settings lost).  We bring up simnets prior to VLANs/Aggrs
# to enable creation of VLANs/Aggrs over simnets.
#
/sbin/dladm up-simnet
/sbin/dladm up-aggr
/sbin/dladm up-vlan
/sbin/dladm up-part
/sbin/dladm init-secobj
/sbin/dladm up-vnic
/sbin/flowadm init-flow

exit $SMF_EXIT_OK
